/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.hadoop.mapreduce.jobhistory;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class JhCounterGroup extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5105530242564101811L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JhCounterGroup\",\"namespace\":\"org.apache.hadoop.mapreduce.jobhistory\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"displayName\",\"type\":\"string\"},{\"name\":\"counts\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"JhCounter\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"displayName\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"long\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<JhCounterGroup> ENCODER =
      new BinaryMessageEncoder<JhCounterGroup>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<JhCounterGroup> DECODER =
      new BinaryMessageDecoder<JhCounterGroup>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<JhCounterGroup> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<JhCounterGroup> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<JhCounterGroup>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this JhCounterGroup to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a JhCounterGroup from a ByteBuffer. */
  public static JhCounterGroup fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence displayName;
  @Deprecated public java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> counts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JhCounterGroup() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param displayName The new value for displayName
   * @param counts The new value for counts
   */
  public JhCounterGroup(java.lang.CharSequence name, java.lang.CharSequence displayName, java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> counts) {
    this.name = name;
    this.displayName = displayName;
    this.counts = counts;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return displayName;
    case 2: return counts;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: displayName = (java.lang.CharSequence)value$; break;
    case 2: counts = (java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'displayName' field.
   * @return The value of the 'displayName' field.
   */
  public java.lang.CharSequence getDisplayName() {
    return displayName;
  }

  /**
   * Sets the value of the 'displayName' field.
   * @param value the value to set.
   */
  public void setDisplayName(java.lang.CharSequence value) {
    this.displayName = value;
  }

  /**
   * Gets the value of the 'counts' field.
   * @return The value of the 'counts' field.
   */
  public java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> getCounts() {
    return counts;
  }

  /**
   * Sets the value of the 'counts' field.
   * @param value the value to set.
   */
  public void setCounts(java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> value) {
    this.counts = value;
  }

  /**
   * Creates a new JhCounterGroup RecordBuilder.
   * @return A new JhCounterGroup RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder newBuilder() {
    return new org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder();
  }

  /**
   * Creates a new JhCounterGroup RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JhCounterGroup RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder other) {
    return new org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder(other);
  }

  /**
   * Creates a new JhCounterGroup RecordBuilder by copying an existing JhCounterGroup instance.
   * @param other The existing instance to copy.
   * @return A new JhCounterGroup RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup other) {
    return new org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder(other);
  }

  /**
   * RecordBuilder for JhCounterGroup instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JhCounterGroup>
    implements org.apache.avro.data.RecordBuilder<JhCounterGroup> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence displayName;
    private java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> counts;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.displayName)) {
        this.displayName = data().deepCopy(fields()[1].schema(), other.displayName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.counts)) {
        this.counts = data().deepCopy(fields()[2].schema(), other.counts);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing JhCounterGroup instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.displayName)) {
        this.displayName = data().deepCopy(fields()[1].schema(), other.displayName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.counts)) {
        this.counts = data().deepCopy(fields()[2].schema(), other.counts);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'displayName' field.
      * @return The value.
      */
    public java.lang.CharSequence getDisplayName() {
      return displayName;
    }

    /**
      * Sets the value of the 'displayName' field.
      * @param value The value of 'displayName'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder setDisplayName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.displayName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'displayName' field has been set.
      * @return True if the 'displayName' field has been set, false otherwise.
      */
    public boolean hasDisplayName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'displayName' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder clearDisplayName() {
      displayName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'counts' field.
      * @return The value.
      */
    public java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> getCounts() {
      return counts;
    }

    /**
      * Sets the value of the 'counts' field.
      * @param value The value of 'counts'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder setCounts(java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter> value) {
      validate(fields()[2], value);
      this.counts = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'counts' field has been set.
      * @return True if the 'counts' field has been set, false otherwise.
      */
    public boolean hasCounts() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'counts' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup.Builder clearCounts() {
      counts = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JhCounterGroup build() {
      try {
        JhCounterGroup record = new JhCounterGroup();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.displayName = fieldSetFlags()[1] ? this.displayName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.counts = fieldSetFlags()[2] ? this.counts : (java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounter>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<JhCounterGroup>
    WRITER$ = (org.apache.avro.io.DatumWriter<JhCounterGroup>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<JhCounterGroup>
    READER$ = (org.apache.avro.io.DatumReader<JhCounterGroup>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
