/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.hadoop.mapreduce.jobhistory;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class JhCounters extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7965848234724533731L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JhCounters\",\"namespace\":\"org.apache.hadoop.mapreduce.jobhistory\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"groups\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"JhCounterGroup\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"displayName\",\"type\":\"string\"},{\"name\":\"counts\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"JhCounter\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"displayName\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"long\"}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<JhCounters> ENCODER =
      new BinaryMessageEncoder<JhCounters>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<JhCounters> DECODER =
      new BinaryMessageDecoder<JhCounters>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<JhCounters> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<JhCounters> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<JhCounters>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this JhCounters to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a JhCounters from a ByteBuffer. */
  public static JhCounters fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> groups;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JhCounters() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param groups The new value for groups
   */
  public JhCounters(java.lang.CharSequence name, java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> groups) {
    this.name = name;
    this.groups = groups;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return groups;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: groups = (java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'groups' field.
   * @return The value of the 'groups' field.
   */
  public java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> getGroups() {
    return groups;
  }

  /**
   * Sets the value of the 'groups' field.
   * @param value the value to set.
   */
  public void setGroups(java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> value) {
    this.groups = value;
  }

  /**
   * Creates a new JhCounters RecordBuilder.
   * @return A new JhCounters RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder newBuilder() {
    return new org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder();
  }

  /**
   * Creates a new JhCounters RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JhCounters RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder other) {
    return new org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder(other);
  }

  /**
   * Creates a new JhCounters RecordBuilder by copying an existing JhCounters instance.
   * @param other The existing instance to copy.
   * @return A new JhCounters RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.JhCounters other) {
    return new org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder(other);
  }

  /**
   * RecordBuilder for JhCounters instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JhCounters>
    implements org.apache.avro.data.RecordBuilder<JhCounters> {

    private java.lang.CharSequence name;
    private java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> groups;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groups)) {
        this.groups = data().deepCopy(fields()[1].schema(), other.groups);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing JhCounters instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.JhCounters other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groups)) {
        this.groups = data().deepCopy(fields()[1].schema(), other.groups);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'groups' field.
      * @return The value.
      */
    public java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> getGroups() {
      return groups;
    }

    /**
      * Sets the value of the 'groups' field.
      * @param value The value of 'groups'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder setGroups(java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup> value) {
      validate(fields()[1], value);
      this.groups = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'groups' field has been set.
      * @return True if the 'groups' field has been set, false otherwise.
      */
    public boolean hasGroups() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'groups' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JhCounters.Builder clearGroups() {
      groups = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JhCounters build() {
      try {
        JhCounters record = new JhCounters();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.groups = fieldSetFlags()[1] ? this.groups : (java.util.List<org.apache.hadoop.mapreduce.jobhistory.JhCounterGroup>) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<JhCounters>
    WRITER$ = (org.apache.avro.io.DatumWriter<JhCounters>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<JhCounters>
    READER$ = (org.apache.avro.io.DatumReader<JhCounters>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
