/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.hadoop.mapreduce.jobhistory;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class JobStatusChanged extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4018939135407646725L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"JobStatusChanged\",\"namespace\":\"org.apache.hadoop.mapreduce.jobhistory\",\"fields\":[{\"name\":\"jobid\",\"type\":\"string\"},{\"name\":\"jobStatus\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<JobStatusChanged> ENCODER =
      new BinaryMessageEncoder<JobStatusChanged>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<JobStatusChanged> DECODER =
      new BinaryMessageDecoder<JobStatusChanged>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<JobStatusChanged> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<JobStatusChanged> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<JobStatusChanged>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this JobStatusChanged to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a JobStatusChanged from a ByteBuffer. */
  public static JobStatusChanged fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence jobid;
  @Deprecated public java.lang.CharSequence jobStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public JobStatusChanged() {}

  /**
   * All-args constructor.
   * @param jobid The new value for jobid
   * @param jobStatus The new value for jobStatus
   */
  public JobStatusChanged(java.lang.CharSequence jobid, java.lang.CharSequence jobStatus) {
    this.jobid = jobid;
    this.jobStatus = jobStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jobid;
    case 1: return jobStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jobid = (java.lang.CharSequence)value$; break;
    case 1: jobStatus = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'jobid' field.
   * @return The value of the 'jobid' field.
   */
  public java.lang.CharSequence getJobid() {
    return jobid;
  }

  /**
   * Sets the value of the 'jobid' field.
   * @param value the value to set.
   */
  public void setJobid(java.lang.CharSequence value) {
    this.jobid = value;
  }

  /**
   * Gets the value of the 'jobStatus' field.
   * @return The value of the 'jobStatus' field.
   */
  public java.lang.CharSequence getJobStatus() {
    return jobStatus;
  }

  /**
   * Sets the value of the 'jobStatus' field.
   * @param value the value to set.
   */
  public void setJobStatus(java.lang.CharSequence value) {
    this.jobStatus = value;
  }

  /**
   * Creates a new JobStatusChanged RecordBuilder.
   * @return A new JobStatusChanged RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder newBuilder() {
    return new org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder();
  }

  /**
   * Creates a new JobStatusChanged RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new JobStatusChanged RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder other) {
    return new org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder(other);
  }

  /**
   * Creates a new JobStatusChanged RecordBuilder by copying an existing JobStatusChanged instance.
   * @param other The existing instance to copy.
   * @return A new JobStatusChanged RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged other) {
    return new org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder(other);
  }

  /**
   * RecordBuilder for JobStatusChanged instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<JobStatusChanged>
    implements org.apache.avro.data.RecordBuilder<JobStatusChanged> {

    private java.lang.CharSequence jobid;
    private java.lang.CharSequence jobStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.jobid)) {
        this.jobid = data().deepCopy(fields()[0].schema(), other.jobid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jobStatus)) {
        this.jobStatus = data().deepCopy(fields()[1].schema(), other.jobStatus);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing JobStatusChanged instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.jobid)) {
        this.jobid = data().deepCopy(fields()[0].schema(), other.jobid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jobStatus)) {
        this.jobStatus = data().deepCopy(fields()[1].schema(), other.jobStatus);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'jobid' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobid() {
      return jobid;
    }

    /**
      * Sets the value of the 'jobid' field.
      * @param value The value of 'jobid'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder setJobid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.jobid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'jobid' field has been set.
      * @return True if the 'jobid' field has been set, false otherwise.
      */
    public boolean hasJobid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'jobid' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder clearJobid() {
      jobid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'jobStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobStatus() {
      return jobStatus;
    }

    /**
      * Sets the value of the 'jobStatus' field.
      * @param value The value of 'jobStatus'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder setJobStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.jobStatus = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'jobStatus' field has been set.
      * @return True if the 'jobStatus' field has been set, false otherwise.
      */
    public boolean hasJobStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'jobStatus' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.JobStatusChanged.Builder clearJobStatus() {
      jobStatus = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public JobStatusChanged build() {
      try {
        JobStatusChanged record = new JobStatusChanged();
        record.jobid = fieldSetFlags()[0] ? this.jobid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.jobStatus = fieldSetFlags()[1] ? this.jobStatus : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<JobStatusChanged>
    WRITER$ = (org.apache.avro.io.DatumWriter<JobStatusChanged>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<JobStatusChanged>
    READER$ = (org.apache.avro.io.DatumReader<JobStatusChanged>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
