/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.hadoop.mapreduce.jobhistory;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TaskUpdated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5995209250340928557L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TaskUpdated\",\"namespace\":\"org.apache.hadoop.mapreduce.jobhistory\",\"fields\":[{\"name\":\"taskid\",\"type\":\"string\"},{\"name\":\"finishTime\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TaskUpdated> ENCODER =
      new BinaryMessageEncoder<TaskUpdated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TaskUpdated> DECODER =
      new BinaryMessageDecoder<TaskUpdated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TaskUpdated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TaskUpdated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TaskUpdated>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TaskUpdated to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TaskUpdated from a ByteBuffer. */
  public static TaskUpdated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence taskid;
  @Deprecated public long finishTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TaskUpdated() {}

  /**
   * All-args constructor.
   * @param taskid The new value for taskid
   * @param finishTime The new value for finishTime
   */
  public TaskUpdated(java.lang.CharSequence taskid, java.lang.Long finishTime) {
    this.taskid = taskid;
    this.finishTime = finishTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return taskid;
    case 1: return finishTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: taskid = (java.lang.CharSequence)value$; break;
    case 1: finishTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'taskid' field.
   * @return The value of the 'taskid' field.
   */
  public java.lang.CharSequence getTaskid() {
    return taskid;
  }

  /**
   * Sets the value of the 'taskid' field.
   * @param value the value to set.
   */
  public void setTaskid(java.lang.CharSequence value) {
    this.taskid = value;
  }

  /**
   * Gets the value of the 'finishTime' field.
   * @return The value of the 'finishTime' field.
   */
  public java.lang.Long getFinishTime() {
    return finishTime;
  }

  /**
   * Sets the value of the 'finishTime' field.
   * @param value the value to set.
   */
  public void setFinishTime(java.lang.Long value) {
    this.finishTime = value;
  }

  /**
   * Creates a new TaskUpdated RecordBuilder.
   * @return A new TaskUpdated RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder newBuilder() {
    return new org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder();
  }

  /**
   * Creates a new TaskUpdated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TaskUpdated RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder other) {
    return new org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder(other);
  }

  /**
   * Creates a new TaskUpdated RecordBuilder by copying an existing TaskUpdated instance.
   * @param other The existing instance to copy.
   * @return A new TaskUpdated RecordBuilder
   */
  public static org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder newBuilder(org.apache.hadoop.mapreduce.jobhistory.TaskUpdated other) {
    return new org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder(other);
  }

  /**
   * RecordBuilder for TaskUpdated instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TaskUpdated>
    implements org.apache.avro.data.RecordBuilder<TaskUpdated> {

    private java.lang.CharSequence taskid;
    private long finishTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.taskid)) {
        this.taskid = data().deepCopy(fields()[0].schema(), other.taskid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.finishTime)) {
        this.finishTime = data().deepCopy(fields()[1].schema(), other.finishTime);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TaskUpdated instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.hadoop.mapreduce.jobhistory.TaskUpdated other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.taskid)) {
        this.taskid = data().deepCopy(fields()[0].schema(), other.taskid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.finishTime)) {
        this.finishTime = data().deepCopy(fields()[1].schema(), other.finishTime);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'taskid' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaskid() {
      return taskid;
    }

    /**
      * Sets the value of the 'taskid' field.
      * @param value The value of 'taskid'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder setTaskid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.taskid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'taskid' field has been set.
      * @return True if the 'taskid' field has been set, false otherwise.
      */
    public boolean hasTaskid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'taskid' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder clearTaskid() {
      taskid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'finishTime' field.
      * @return The value.
      */
    public java.lang.Long getFinishTime() {
      return finishTime;
    }

    /**
      * Sets the value of the 'finishTime' field.
      * @param value The value of 'finishTime'.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder setFinishTime(long value) {
      validate(fields()[1], value);
      this.finishTime = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'finishTime' field has been set.
      * @return True if the 'finishTime' field has been set, false otherwise.
      */
    public boolean hasFinishTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'finishTime' field.
      * @return This builder.
      */
    public org.apache.hadoop.mapreduce.jobhistory.TaskUpdated.Builder clearFinishTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TaskUpdated build() {
      try {
        TaskUpdated record = new TaskUpdated();
        record.taskid = fieldSetFlags()[0] ? this.taskid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.finishTime = fieldSetFlags()[1] ? this.finishTime : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TaskUpdated>
    WRITER$ = (org.apache.avro.io.DatumWriter<TaskUpdated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TaskUpdated>
    READER$ = (org.apache.avro.io.DatumReader<TaskUpdated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
